[project]
name = "query_korean_school"
version = "0.1.0"
description = "Power up your crews with query_korean_school"
readme = "README.md"
requires-python = ">=3.10,<3.14"
dependencies = [
    "crewai[tools]>=0.203.1"
]

[tool.crewai]
type = "tool"
